### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by eternal-flame-AD** [pea3nut/pxer-homepage#5]
It was just so annoying to see ISP injecting ads into your beautifully-designed website.

**Comment by eternal-flame-AD** [comment]
BTW, the current configuration could cause problems to users using add-ons like `HTTPS Everywhere` as they always attempt to rewrite URLs to their HTTPS equivalent. I think using `virtual host` is a better idea.

**Comment by pea3nut** [comment]
No.

1. The website has no Form anywhere.
2. Add costing additional.
